# Generated by Django 6.0.2 on 2026-05-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("org_number", models.CharField(max_length=256)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("next_journal_number", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("entry_date", models.DateField(blank=True, null=True)),
                (
                    "journal_number",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="invoices_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="SEK", max_length=3, null=True
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices_app.journal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=10)),
                ("debit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("credit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_lines",
                        to="invoices_app.journal",
                    ),
                ),
            ],
        ),
    ]
