# Generated by Django 6.0.2 on 2026-05-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("org_number", models.CharField(max_length=256)),
                ("address", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=256)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="SEK", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("supplier", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="invoices/")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="invoices_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=10)),
                ("debit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("credit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_lines",
                        to="invoices_app.invoice",
                    ),
                ),
            ],
        ),
    ]
