# Generated by Django 6.0.2 on 2026-05-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountingline",
            old_name="invoice",
            new_name="jornal",
        ),
    ]
