# Generated by Django 6.0.2 on 2026-05-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0002_rename_invoice_accountingline_jornal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountingline",
            old_name="jornal",
            new_name="journal",
        ),
    ]
