# Generated by Django 6.0.2 on 2026-05-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0003_rename_jornal_accountingline_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices_app.journal",
            ),
        ),
    ]
