# Generated by Django 6.0.2 on 2026-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0004_alter_invoice_journal"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("invoice", "Invoice"),
                    ("bank", "Bank transaction"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
