# Generated by Django 6.0.2 on 2026-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0006_alter_journal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingline",
            name="vat_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
