# Generated by Django 6.0.2 on 2026-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0007_accountingline_vat_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountingline",
            name="vat_code",
        ),
        migrations.AddField(
            model_name="journal",
            name="vat_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
