# Generated by Django 6.0.2 on 2026-05-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0008_remove_accountingline_vat_code_journal_vat_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="invoices_app.journal",
            ),
        ),
    ]
