# Generated by Django 6.0.2 on 2026-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0009_alter_invoice_journal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
