# Generated by Django 6.0.2 on 2026-06-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0010_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingline",
            name="description",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
